"""Generate an inventory of MCAP fixtures.

Walks every .mcap file in sample_data/mcap/ and emits a Markdown table at
tests/fixtures/mcap/INVENTORY.md describing profile, channels, schemas,
message counts, compression, presence of summary section, and attachments.

Run from repo root:
    python scripts/mcap_inventory.py
"""

from __future__ import annotations

from collections import Counter
from pathlib import Path

from mcap.reader import make_reader

REPO = Path(__file__).resolve().parent.parent
FIXTURES_DIR = REPO / "sample_data" / "mcap"
OUTPUT = REPO / "tests" / "fixtures" / "mcap" / "INVENTORY.md"


def inspect_file(path: Path) -> dict:
    size = path.stat().st_size
    with path.open("rb") as f:
        reader = make_reader(f)
        summary = reader.get_summary()
        header = reader.get_header()

        profile = header.profile or "(none)"

        channels = []
        message_counts: Counter[int] = Counter()
        compressions: set[str] = set()
        attachments = []
        has_summary = summary is not None
        has_message_index = False

        if summary is not None:
            for chan_id, chan in summary.channels.items():
                schema = summary.schemas.get(chan.schema_id)
                channels.append(
                    {
                        "topic": chan.topic,
                        "schema_name": schema.name if schema else "",
                        "schema_encoding": schema.encoding if schema else "",
                        "message_encoding": chan.message_encoding,
                    }
                )
            for stat_chan_id, count in summary.statistics.channel_message_counts.items():
                message_counts[stat_chan_id] = count
            for chunk_index in summary.chunk_indexes:
                compressions.add(chunk_index.compression or "none")
            has_message_index = bool(summary.statistics.message_count) and any(
                ci.message_index_offsets for ci in summary.chunk_indexes
            )
            for att in summary.attachment_indexes:
                attachments.append(
                    {
                        "name": att.name,
                        "media_type": att.media_type,
                        "size": att.data_size,
                    }
                )

        # Fallback: walk channels by streaming if no summary.
        if not channels:
            seen: dict[int, dict] = {}
            for schema, channel, _msg in reader.iter_messages():
                if channel.id in seen:
                    continue
                seen[channel.id] = {
                    "topic": channel.topic,
                    "schema_name": schema.name if schema else "",
                    "schema_encoding": schema.encoding if schema else "",
                    "message_encoding": channel.message_encoding,
                }
                message_counts[channel.id] += 1
            channels = list(seen.values())

    return {
        "name": path.name,
        "size_bytes": size,
        "profile": profile,
        "channels": channels,
        "total_messages": sum(message_counts.values()),
        "compressions": sorted(compressions) or ["unknown"],
        "has_summary": has_summary,
        "has_message_index": has_message_index,
        "attachments": attachments,
    }


def render(inventories: list[dict]) -> str:
    lines: list[str] = []
    lines.append("# MCAP Fixture Inventory")
    lines.append("")
    lines.append(
        "Auto-generated by `scripts/mcap_inventory.py` from files in "
        "`sample_data/mcap/`. Do not edit by hand."
    )
    lines.append("")
    lines.append("## Summary")
    lines.append("")
    lines.append("| File | Size | Profile | Channels | Messages | Compression | Summary | Index | Attachments |")
    lines.append("|---|---|---|---|---|---|---|---|---|")
    for inv in inventories:
        lines.append(
            "| `{name}` | {size:.2f} MB | {profile} | {nch} | {nmsg} | {comp} | {summ} | {idx} | {natt} |".format(
                name=inv["name"],
                size=inv["size_bytes"] / 1_000_000,
                profile=inv["profile"],
                nch=len(inv["channels"]),
                nmsg=inv["total_messages"],
                comp=", ".join(inv["compressions"]),
                summ="yes" if inv["has_summary"] else "no",
                idx="yes" if inv["has_message_index"] else "no",
                natt=len(inv["attachments"]),
            )
        )
    lines.append("")

    for inv in inventories:
        lines.append(f"## `{inv['name']}`")
        lines.append("")
        lines.append(f"- Profile: `{inv['profile']}`")
        lines.append(f"- Size: {inv['size_bytes'] / 1_000_000:.2f} MB")
        lines.append(f"- Total messages: {inv['total_messages']}")
        lines.append(f"- Compression: {', '.join(inv['compressions'])}")
        lines.append(f"- Summary section: {'yes' if inv['has_summary'] else 'no'}")
        lines.append(f"- Message index: {'yes' if inv['has_message_index'] else 'no'}")
        lines.append("")
        lines.append("| Topic | Schema | Schema encoding | Message encoding |")
        lines.append("|---|---|---|---|")
        for c in sorted(inv["channels"], key=lambda x: x["topic"]):
            lines.append(
                "| `{topic}` | `{schema}` | {senc} | {menc} |".format(
                    topic=c["topic"],
                    schema=c["schema_name"] or "(none)",
                    senc=c["schema_encoding"] or "-",
                    menc=c["message_encoding"] or "-",
                )
            )
        lines.append("")
        if inv["attachments"]:
            lines.append("**Attachments:**")
            for a in inv["attachments"]:
                lines.append(f"- `{a['name']}` ({a['media_type']}, {a['size']} bytes)")
            lines.append("")

    return "\n".join(lines) + "\n"


def main() -> None:
    files = sorted(FIXTURES_DIR.glob("*.mcap"))
    if not files:
        raise SystemExit(f"No MCAP fixtures found in {FIXTURES_DIR}")
    inventories = [inspect_file(p) for p in files]
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(render(inventories))
    print(f"Wrote {OUTPUT} ({len(inventories)} files)")


if __name__ == "__main__":
    main()
